## Applying linear filter

In [2]:
import cv2;
import numpy;

In [12]:
# 3*3 kernel for smoothing 
kernel = [[0, 1, 0], [1, 4, 1], [0, 1, 0]]
print(kernel)
print(type(kernel))
k = numpy.array([[0,1,0], [1,4,1], [0,1,0]])
print(k)
print(type(k))

[[0, 1, 0], [1, 4, 1], [0, 1, 0]]
<class 'list'>
[[0 1 0]
 [1 4 1]
 [0 1 0]]
<class 'numpy.ndarray'>


In [17]:
# load image
image = cv2.imread('charizard.png')
cv2.imshow("Original image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
grey = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) 
cv2.imshow("greyscale", grey)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Things to note about the filter2D option
it takes a numpy array for the kernel

In [20]:
# takes 3 params: source image, ddepth, kernel
# ddepth is the depth of destination image -1 means the same as the original
# filter = cv2.filter2D(image, -1, kernel)
# only the wings show up, why?
filter = cv2.filter2D(image, -1, k)
cv2.imshow("Filtered image", filter)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# something is wrong, this shows nothing
gfilter = cv2.filter2D(grey, -1, k)
cv2.imshow("Filtered grey image", gfilter)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# trying an edge detection kernel
# this one worked, maybe my previous kernel was faulty
edge = numpy.array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]])
img = cv2.imread('felix.png')
cv2.imshow('Original', img)
cv2.waitKey(0)
fil = cv2.filter2D(img, -1, edge)
cv2.imshow('Edges of the image', fil)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# testing sharpen kernel
cath = cv2.imread('cathedral.jpg')
# cv2.imshow('Original', cath)
# cv2.waitKey(0)

# original image is too big for me to see things clearly
width = int(cath.shape[1]/3)
height = int(cath.shape[0]/3)
scale  = (width, height)
scaleDown = cv2.resize(cath, scale)
cv2.imshow('Resized', scaleDown)
cv2.waitKey(0)

# applying sharpen kernel
sharpen = numpy.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
conv = cv2.filter2D(scaleDown, -1, sharpen)
cv2.imshow('Sharpen', conv)
cv2.waitKey(0)
cv2.destroyAllWindows()